# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce04024fe5a86b2a3fb5ed8044e1029ae173ef6030ff0fd579d2bd10cc9da8d1b95d668524410f94e700f176599922285767d94c2955b03b11786eded593fbe5

test:
  secret_key_base: 9805775de6769c9491b85c1afccba3636d78406f2d4a804463dc9cc364cb8e9da57afe52cf0cd516c4596f61645fcce2720a85e139bc8618146ccbb287b03cd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
